name: Ansible Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код из репозитория
        uses: actions/checkout@v3

      - name: Установить Ansible
        run: pip install ansible ansible-lint

      - name: Установить роли из requirements.yml
        run: ansible-galaxy install -r requirements.yml

      - name: Проверить плейбуки
        run: ansible-lint playbooks/
